// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PetGuardian.Infrastructure.Persistence;

#nullable disable

namespace PetGuardian.Infrastructure.Migrations
{
    [DbContext(typeof(PetGuardianContext))]
    partial class PetGuardianContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetGuardian.Domain.Entities.Atendimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_atendimento");

                    b.Property<string>("Anotacoes")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("anotacoes");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data");

                    b.Property<Guid>("PetId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("pet_id_pet");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("status_id_status");

                    b.Property<Guid>("TipoAtendId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("tipo_atend_id_tipo_atend");

                    b.Property<decimal>("Valor")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("valor");

                    b.Property<Guid>("VeterinarioId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("veterinario_id_veterinario");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TipoAtendId");

                    b.HasIndex("VeterinarioId");

                    b.ToTable("atendimento", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Bairro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_bairro");

                    b.Property<Guid>("CidadeId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("cidade_id_cidade");

                    b.Property<string>("NomeBairro")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("nome_bairro");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.ToTable("bairro", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Cidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_cidade");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("estado_id_estado");

                    b.Property<string>("NomeCidade")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("nome_cidade");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("cidade", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Clinica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_clinica");

                    b.Property<Guid>("EnderecoId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("endereco_id_endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("nome");

                    b.Property<Guid>("TelefoneId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("telefone_id_telefone");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId")
                        .IsUnique();

                    b.HasIndex("TelefoneId")
                        .IsUnique();

                    b.ToTable("clinica", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_endereco");

                    b.Property<Guid>("BairroId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("bairro_id_bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)")
                        .HasColumnName("cep");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("NVARCHAR2(5)")
                        .HasColumnName("numero");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("rua");

                    b.HasKey("Id");

                    b.HasIndex("BairroId");

                    b.ToTable("endereco", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Estado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_estado");

                    b.Property<string>("NomeEstado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("nome_estado");

                    b.HasKey("Id");

                    b.ToTable("estado", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_pet");

                    b.Property<string>("Castrado")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("castrado");

                    b.Property<byte>("Idade")
                        .HasColumnType("NUMBER(2)")
                        .HasColumnName("idade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("nome");

                    b.Property<string>("Porte")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("porte");

                    b.Property<Guid>("RacaId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("raca_id_raca");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("sexo");

                    b.HasKey("Id");

                    b.HasIndex("RacaId");

                    b.ToTable("pet", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Raca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_raca");

                    b.Property<string>("NomeRaca")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("nome_raca");

                    b.HasKey("Id");

                    b.ToTable("raca", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_status");

                    b.Property<string>("NomeStatus")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("nome_status");

                    b.HasKey("Id");

                    b.ToTable("status", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Tarefa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_tarefa");

                    b.Property<DateTime?>("Conclusao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("conclusao");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("PetId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("pet_id_pet");

                    b.Property<byte>("PontosTarefa")
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("pontos_tarefa");

                    b.Property<DateTime>("Prazo")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("prazo");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("status_id_status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("titulo");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("usuario_id_usuario");

                    b.Property<Guid>("VeterinarioId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("veterinario_id_veterinario");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VeterinarioId");

                    b.ToTable("tarefa", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Telefone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_telefone");

                    b.Property<string>("NumDdd")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("num_ddd");

                    b.Property<string>("NumTel")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("NVARCHAR2(9)")
                        .HasColumnName("num_tel");

                    b.HasKey("Id");

                    b.ToTable("telefone", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.TipoAtend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_tipo_atend");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("tipo_atend", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("senha");

                    b.Property<Guid>("TelefoneId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("telefone_id_telefone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TelefoneId")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.UsuarioEndereco", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("usuario_id_usuario");

                    b.Property<Guid>("EnderecoId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("endereco_id_endereco");

                    b.HasKey("UsuarioId", "EnderecoId");

                    b.HasIndex("EnderecoId");

                    b.ToTable("usuario_endereco", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.UsuarioPet", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("usuario_id_usuario");

                    b.Property<Guid>("PetId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("pet_id_pet");

                    b.Property<string>("ResponPrinc")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("respon_princ");

                    b.HasKey("UsuarioId", "PetId");

                    b.HasIndex("PetId");

                    b.ToTable("usuario_pet", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Veterinario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_veterinario");

                    b.Property<Guid?>("ClinicaId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("clinica_id_clinica");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("senha");

                    b.Property<Guid>("TelefoneId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("telefone_id_telefone");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TelefoneId")
                        .IsUnique();

                    b.ToTable("veterinario", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Atendimento", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Pet", "Pet")
                        .WithMany("Atendimentos")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetGuardian.Domain.Entities.Status", "Status")
                        .WithMany("Atendimentos")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetGuardian.Domain.Entities.TipoAtend", "TipoAtend")
                        .WithMany("Atendimentos")
                        .HasForeignKey("TipoAtendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetGuardian.Domain.Entities.Veterinario", "Veterinario")
                        .WithMany("Atendimentos")
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Status");

                    b.Navigation("TipoAtend");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Bairro", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Cidade", "Cidade")
                        .WithMany("Bairros")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Cidade", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Clinica", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Endereco", "Endereco")
                        .WithOne()
                        .HasForeignKey("PetGuardian.Domain.Entities.Clinica", "EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetGuardian.Domain.Entities.Telefone", "Telefone")
                        .WithOne()
                        .HasForeignKey("PetGuardian.Domain.Entities.Clinica", "TelefoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("Telefone");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Endereco", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Bairro", "Bairro")
                        .WithMany("Enderecos")
                        .HasForeignKey("BairroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bairro");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Pet", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Raca", "Raca")
                        .WithMany("Pets")
                        .HasForeignKey("RacaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Raca");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Tarefa", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Pet", "Pet")
                        .WithMany("Tarefas")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetGuardian.Domain.Entities.Status", "Status")
                        .WithMany("Tarefas")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetGuardian.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Tarefas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PetGuardian.Domain.Entities.Veterinario", "Veterinario")
                        .WithMany("Tarefas")
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Status");

                    b.Navigation("Usuario");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Telefone", "Telefone")
                        .WithOne()
                        .HasForeignKey("PetGuardian.Domain.Entities.Usuario", "TelefoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Telefone");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.UsuarioEndereco", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetGuardian.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Enderecos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.UsuarioPet", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Pet", "Pet")
                        .WithMany("UsuariosPet")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetGuardian.Domain.Entities.Usuario", "Usuario")
                        .WithMany("PetsVinculados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Veterinario", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Clinica", "Clinica")
                        .WithMany("Veterinarios")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PetGuardian.Domain.Entities.Telefone", "Telefone")
                        .WithOne()
                        .HasForeignKey("PetGuardian.Domain.Entities.Veterinario", "TelefoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinica");

                    b.Navigation("Telefone");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Bairro", b =>
                {
                    b.Navigation("Enderecos");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Cidade", b =>
                {
                    b.Navigation("Bairros");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Clinica", b =>
                {
                    b.Navigation("Veterinarios");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Estado", b =>
                {
                    b.Navigation("Cidades");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Pet", b =>
                {
                    b.Navigation("Atendimentos");

                    b.Navigation("Tarefas");

                    b.Navigation("UsuariosPet");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Raca", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Status", b =>
                {
                    b.Navigation("Atendimentos");

                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.TipoAtend", b =>
                {
                    b.Navigation("Atendimentos");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Enderecos");

                    b.Navigation("PetsVinculados");

                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Veterinario", b =>
                {
                    b.Navigation("Atendimentos");

                    b.Navigation("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
